autolabeler:
  - label: "bug"
    branch:
      - '/^fix/'
    title:
      - "/^fix/i"
  - label: "enhancement"
    branch:
      - '/^feature/'
    title:
      - "/^feature/i"
categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking-change'
  - title: 'Features'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'deployment'
      - 'translation'
  - title: 'Dependencies'
    collapse-after: 3
    label: 'dependencies'
include-labels:
  - 'enhancement'
  - 'bug'
  - 'chore'
  - 'deployment'
  - 'translation'
  - 'dependencies'
replacers: # Changes "Feature: Update checker" to "Update checker"
  - search: '/Feature:|Feat:|\[feature\]/gi'
    replace: ''
category-template: '### $TITLE'
change-template: '- $TITLE [@$AUTHOR](https://github.com/$AUTHOR) ([#$NUMBER]($URL))'
change-title-escapes: '\<*_&#@'
template: |
  ## paperless-ngx $RESOLVED_VERSION

  $CHANGES
